### ISSUE TITLE
Editing Encumbrance

### ISSUE THREAD

**Issue by zeldafreak6245** [sw5e-foundry/sw5e#701] opened 2023-07-27 13:52 UTC
**Describe the bug**
Source: Discord
OP: Biggus Dicqus
Date: 11/12/2022

Hello, quick question. I added the Brawny attribute to my character but it doesn't appear to have modified my encumbrance max. I found I was able to add the racial bonus "Powerful build" under Special Traits.I have both powerful build as a Dowutin but also have brawny, so I need the encumbrance to be tripled instead of doubled. Is it possible to edit the encumbrance value? From what searching I did I found for 5e the Attribute key for encumbrance is data.attributes.encumbrance.max but I cannot get that to work. Thanks.

**Foundry Information
Foundry version: V9
SW5e version: N/A
OS: N/A

**Comment by Ikaguia** [comment] 2023-08-21 18:03
duplicate of #704

**Closed by Ikaguia** 2023-08-21 18:03 UTC
Labels: bug
