### ISSUE TITLE
Cannot create and duplicate character and starship sheet on Oracle Cloud Hosting (Ubuntu OS)

### ISSUE THREAD

**Issue by DwarFenny** [sw5e-foundry/sw5e#794] opened 2023-12-11 15:10 UTC
**Describe the bug**
I can't create Character sheet and Starship sheet (Getting two different errors) on Oracle Cloud Hosting (Ubuntu OS)

**To Reproduce**
1. Click "Create Actor"
2. Choose either "Player Character" or "Starship"
3. See the error and no Player or Starship sheet

**Expected behavior**
Create Character or Starship sheet

**Screenshots**
Actor (Player sheet)
![Picture1](https://github.com/sw5e-foundry/sw5e/assets/85033542/89972a4d-7c51-4519-a974-b3980587f262)
Starship
![Picture2](https://github.com/sw5e-foundry/sw5e/assets/85033542/b8bcb8e1-f477-45cd-82a0-0203781f41cf)

**Foundry Information**
Foundry version: [[V11 Build 315]]
SW5e version: [[2.4.0.2.7.0]]
OS: [[OS Information (Oracle Could Ubuntu Linux)]]

**Additional context**
When I try to create Actor Sheet on local Foundry on Windows 11 or Forge VTT there is no issue there, but when I try to create Actor sheet on Oracle Cloud (Ubuntu) I simply cannot, I tried to make a world on local Foundry and then export it to Oracle, but the issue is still there, I can't make duplicate of this sheet as well (getting the same error) but when I open the sheets from that imported world there is no issue, they're working just fine. Starship sheet cannot be created on either local, forge or on Oracle Cloud on Ubuntu. I tried using different browsers, but there is no difference there.

**Comment by Ikaguia** [comment] 2023-12-12 18:39
@DwarFenny the issue with the starship sheets is an easy one to fix, this post on discord has the info on it: https://discord.com/channels/727847839631278110/1179881298370764882/1179883345283391488

As for the character sheet issue, that one seems to be an error related to a faulty foundry update (there are reports of this happening on other systems such as dnd5e as well). The only known fix for this is to completely uninstall and reinstall foundry.

**Comment by Ikaguia** [comment] 2023-12-12 23:09
Also, duplicate of https://github.com/sw5e-foundry/sw5e/issues/793

**Closed** 2023-12-12 23:09 UTC
Labels: bug, duplicate
